default_language_version:
  python: python3.10

repos:
  - repo: local
    hooks:
      - id: isort
        name: Format code with isort
        entry: isort
        language: system
        always_run: true
        args:
          [
            "--profile=black",
            "--py=311",
            "--line-length=120",
            "--multi-line=3",
            "--trailing-comma",
            "--force-grid-wrap=0",
            "--use-parentheses",
            "--ensure-newline-before-comments",
            "--project=dataramp",
          ]

  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
