repos:
  - repo: local
    hooks:
      - id: whitespace
        name: strip whitespace
        entry: ./strip_whitespaces.sh
        language: system
        always_run: true
        pass_filenames: false
      - id: ruff
        name: ruff
        entry: ruff . --preview
        language: system
        always_run: true
        pass_filenames: false
      # - id: pylint
      #   name: pylint
      #   entry: env PYTHONPATH="." python3 -m pylint dataramp/
      #   language: system
      #   always_run: true
      #   pass_filenames: false
      # - id: mypy
      #   name: mypy
      #   entry: mypy dataramp/ --strict-equality
      #   language: system
      #   always_run: true
      #   pass_filenames: false