repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: python
        types: [python]
        language_version: python3.10
        args: [--line-length=120]

      - id: isort
        name: isort
        entry: isort
        language: python
        types: [python]
        language_version: python3.10
        args: [--line-length=120, --profile black]
