language: python

matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
    - python: 3.8
    - python: 3.9
    - python: 3.10
    - python: 3.11

cache:
    directories:
        - $HOME/.cache/pip

install:
    - python -m venv venv
    - source venv/bin/activate
    - pip install -U pip
