indent-width = 2

lint.select = [
  "F",
  "W6",
  "E71",
  "E72",
  "E112",   # no-indented-block
  "E113",   # unexpected-indentation
  "E203",   # whitespace-before-punctuation
  "E272",   # multiple-spaces-before-keyword
  "E501",   # line-too-long
  "E702",   # multiple-statements-on-one-line-semicolon
  "W191",   # tab-indentation
  "W291",   # trailing-whitespace
  "W293",   # blank-line-with-whitespace
]

line-length = 150

exclude = [
  "examples/",
  "docs/"
]